# Generated by Django 3.1.5 on 2021-06-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_api', '0002_customermaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
